apiVersion: v1
kind: Service
metadata: 
  labels:
    name: lb
  name: lb 
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: frontend
    run: wordpress-deployment
  type: LoadBalancer
